C11.csv, xml/C11.xml
=> Ft21-1-draft.1 > FT21-1-draft

C05.csv, xml/C05.xml
=> Issue68 to FT22-1

C08.csv, xml/C08.xml
=> Issue67 to FT22-1

C02.csv, xml/C02.xml
=> Issue71 to FT22-1

C08.csv, xml/C08.xml
=> Issue61 to FT22-1

C02.csv, xml/C02.xml
=> Issue64 merge to FT22-1

C05.csv, xml/C05.xml
=> Issue63 merge to FT22-1

C08.csv, xml/C08.xml
=> Issue69 merge to FT22-1

C08.csv, xml/C08.xml
=> Issue70 merge into FT22-1 

C05.csv, xml/C05.xml
=> Issue103 into FT branch

C12.csv, xml/C12.xml
=> Issue82 into FT2022-2

C14.csv, xml/C14.xml
=> Issue92 into FT2022-2

C08.csv, xml/C08.xml
=> Issue104 into FT2022-2

C14.csv, xml/C14.xml
=> Issue89 to FT2022-2

C08.csv, xml/C08.xml
=> Issue86 into FT2022-2

C14.csv, xml/C14.xml
=> Issue91 to FT2022-2

C08.csv, xml/C08.xml
=> 113 c08csv new entry to identify gems and omps limb instruments

C03.csv, xml/C03.xml
issue #110 
<table><tbody><tr><td>Additions to Common Code Table C-3 Instrument make and type for water temperature profile measurements</td></tr></tbody></table>
=> 110 additions to common code table C 3

C13.csv, xml/C13.xml
=> 114 c13csv new sub category for aerosol

C12.csv, xml/C12.xml
=> 116 add new entry in common code table c12 to identify noaa satellite operations facility as a sub centre for eumetsat

C13.csv, xml/C13.xml
=> 122 c13 318 addition of new entry for data from ocean gliders

C01.csv, C11.csv, xml/C00.xml, xml/C01.xml, xml/C11.xml
=> 136 new entry in cct 1 and cct 11

C00.csv, C03.csv, xml/C00.xml, xml/C03.xml
=> 115 apex d rbr additions to common code table c 3 instrument make and type for water temperature profile measurements

C03.csv, xml/C00.xml, xml/C03.xml
=> 128 new entry for cct c 3 navis ebr sbe

C03.csv, xml/C00.xml, xml/C03.xml
=> 134 8 new entries for cct c 3 for water temperature sensors

C03.csv, C04.csv, xml/C00.xml
=> 145 cct 3 and cct 4 request by japan

C05.csv, xml/C00.xml, xml/C05.xml
=> 143 cct 05 new codes for fy 3f and fy 3g

C05.csv, xml/C00.xml, xml/C05.xml
=> 137 cct 05 declaration of sentinel 1c and sentinel 1d satellites

C08.csv, xml/C00.xml, xml/C08.xml
=> 129 cct 08 new code for ssh instrument

C08.csv, xml/C00.xml, xml/C08.xml
=> 131 cct 08 new codes for fy 4 giirs fy 4 agri fy 4 ghi fy 3 hiras and fy 3 mwri

C13.csv, xml/C00.xml, xml/C13.xml
=> 132 cct 13 new international data sub category for mw temperaturehumidity sounding

C00.csv, C01.csv, C02.csv, C03.csv, C04.csv, C05.csv, C08.csv, C11.csv, C13.csv, xml/C00.xml, xml/C01.xml, xml/C02.xml, xml/C03.xml, xml/C04.xml, xml/C05.xml, xml/C08.xml, xml/C11.xml, xml/C13.xml
https://github.com/wmo-im/CCT/milestone/9
https://wmoomm.sharepoint.com/:b:/s/wmocpdb/EWNr-muIBC9LgzBIhUoRWP4B57Q0iF5bV8Y_rnyLXW7tFg?e=D459zr
=> FT2023-2 for CCT

C01.csv, C11.csv, xml/C01.xml, xml/C11.xml
=> 158 cct 1 and cct 11 new entry for awi

C08.csv, xml/C08.xml
=> 173 cct 8 eumetsat microwave radiometer mw radiometer swot new entry

C08.csv, xml/C08.xml
=> 172 cct 8 eumetsat eps sterna radiometer mwr aws 1 new entry

C05.csv, C08.csv, xml/C05.xml, xml/C08.xml
=> 167 cct 05 request to add entry to identify aws esas arctic weather satellite

C05.csv, xml/C05.xml
=> 169 cct 05 request to add entry to identify swot cnesnasas surface water and ocean topography satellite

C05.csv, xml/C05.xml
=> 159 cct 05 new entries to identify tempo satellite

C08.csv, xml/C08.xml
=> 160 cct 08 new entry to identify tempo instrument

C08.csv, xml/C08.xml
=> 164 cct 08 request to identify tanso fts2 instrument

C05.csv, xml/C05.xml
=> 163 cct 05 request to identify gosat 2

C13.csv, xml/C13.xml
=> 168 add new cct 13 entry for radio occultation data from non satellites

C02.csv, xml/C02.xml
=> 166 cct 02 new entries to identify radiosondesoundingsystems of china

C05.csv, xml/C05.xml
=> 161 cct 05 request to eumetsat esa ec to identify co2m a satellite

C08.csv, xml/C08.xml
=> 200 cct 08 new codes for windrad on fy 3e and fy 3j

C08.csv, xml/C08.xml
=> 199 update c08csv for cris

C13.csv, xml/C13.xml
=> 198 new entries to c13 sub category to identify tropical cyclone forecast from machine learning

C13.csv, xml/C13.xml
=> 196 new cct c 13 entry for long duration balloon observations

C01.csv, C05.csv, C08.csv, C11.csv, xml/C01.xml, xml/C05.xml, xml/C08.xml, xml/C11.xml
=> 195 new cct c 111 c 5 and c 8 entries for commercial providers of radio occultation data

C01.csv, C05.csv, C08.csv, C11.csv, xml/C01.xml, xml/C05.xml, xml/C08.xml, xml/C11.xml
=> Revert "195 new cct c 111 c 5 and c 8 entries for commercial providers of radio occultation data"

C05.csv, C08.csv, xml/C05.xml, xml/C08.xml
=> 203 new satellites and instrument from japan cct5 and cct8

C01.csv, C11.csv, C12.csv, xml/C01.xml, xml/C11.xml, xml/C12.xml
=> 216 new cct c 111 and c 12 entries for scripps

C08.csv, xml/C08.xml
=> 220 cct 08 request to identify instruments on co2m a

.github/ISSUE_TEMPLATE/amendment-proposal.yml
add text area for data exchange plans and other cleanup
=> Issue template

C11.csv, xml/C11.xml
=> 235 new typo in c11csv

C14.csv, xml/C14.xml
=> 239 c14 gaseous molecules

C05.csv, xml/C05.xml
=> 232 quicksounder

C05.csv, xml/C05.xml
=> Revert "232 quicksounder"

C05.csv, xml/C05.xml
=> new PR for 232 quicksounder
